### ISSUE TITLE
How to make the graph reward/action

### ISSUE THREAD

**Issue by nanbaima** [vitchyr/viskit#14]
Hey Vitchyr,

I have to thank you for your amazing work, it is quite good and well done. 
I have a question, how I may reproduce the reward per number of actions and reward per action graphs?
It would increasingly help me to better achieve my goals and the best way to see what are the responses per action that my simulation take.
Thank you for your attention!

**Comment by vitchyr** [comment]
Which graph exactly?

**Comment by samchenatti** [comment]
It would be really great to have a graph showing how the total number of steps per epoch of the envronment increases through the experiment.

By the way, is the project opened for public contribuitions?

**Comment by vitchyr** [comment]
I'm not sure I understand the concern or request. If this is logged, you
can change the y-axis to show this. Are you asking how to log these numbers
in the first place?

Also, are you coming from rlkit or another repo?

**Comment by nanbaima** [comment]
> Which graph exactly?

Hey Vitchyr,
Sorry for not being clear.
Well, I'm coming from your rlkit repo.

Indeed the information is in the csv file, however I don't see options, when running your script, to be selected at the browser, such as:
- reward/number of actions
- reward/action
- steps per epoch, as well

I mean, at the selection bar at the browser, there are a big list, but not those options.
Are the axis customizable?
Maybe I've missed how to do it, or I'm not using your tool to its fullness.

**Comment by vitchyr** [comment]
If you're looking for more fine-grain logging, then you'll have to implement it yourself. I recommend starting (e.g.) [here for algorithm-specific logs](https://github.com/vitchyr/rlkit/blob/master/rlkit/torch/sac/sac.py#L161) and [here for sampling-specific logs](https://github.com/vitchyr/rlkit/blob/master/rlkit/samplers/data_collector/path_collector.py#L67).

Also, the total number of steps is logged (see `num steps total`), so you can always plot that versus epoch.

**Comment by nanbaima** [comment]
> If you're looking for more fine-grain logging, then you'll have to implement it yourself. I recommend starting (e.g.) [here for algorithm-specific logs](https://github.com/vitchyr/rlkit/blob/master/rlkit/torch/sac/sac.py#L161) and [here for sampling-specific logs](https://github.com/vitchyr/rlkit/blob/master/rlkit/samplers/data_collector/path_collector.py#L67).
> 
> Also, the total number of steps is logged (see `num steps total`), so you can always plot that versus epoch.

Perfectly Vitchyr,

I think this will work.
Thanks for your time,
Once again, nice work!
