### ISSUE TITLE
Getting DeprecationWarning and X_label and Y_label missing

### ISSUE THREAD

**Issue by nanbaima** [vitchyr/viskit#16]
Hey Viskit.
I'm getting this warning when running the script:
`.../.local/lib/python3.6/site-packages/plotly/tools.py:465: DeprecationWarning:

plotly.tools.make_subplots is deprecated, please use plotly.subplots.make_subplots instead
`
And I'm not sure if it is the cause, but perhaps as a consequence the graphs are missing the description of X-axis and Y-axis -labels, it appears [object Object] in both instead of the chosen descriptions of Y-Axis Attributes and X-Axis Attributes.
Do you have any idea, what might it be?

**Comment by vitchyr** [comment]
What version of plotly are you using? I'm using version `3.4.2`.

**Comment by nanbaima** [comment]
Hey Vitchyr,
I saw that the problem is only occurring with early versions of trained data using this same repo.
In other worlds, it is only happening with trained data I acquired last year with an early version, and I was trying to run it with this updated version.
