### ISSUE TITLE
Dependency conflict

### ISSUE THREAD

**Issue by ritalaezza** [vitchyr/viskit#20]
Hello,

When I tried updating viskit, this happened...

The conflict is caused by:
    viskit 0.1 depends on Jinja2==2.11.3
    flask 2.0.1 depends on Jinja2>=3.0

**Comment by zhuliwen** [comment]
I also encountered this error.

**Comment by zhuliwen** [comment]
I modified the code in line 7 in `setup.py`:
```Python
# origin
# REQUIRED_PACKAGES = ['Flask==2.0.1', 'matplotlib==3.4.2', 'plotly==5.1.0', 'numpy==1.21.0', 'Jinja2==2.11.3']
# new
REQUIRED_PACKAGES = ['Flask==2.0.1', 'matplotlib==3.4.2', 'plotly==5.1.0', 'numpy==1.21.0']
```
Then it succeeded.

**Comment by DazhiZhong** [comment]
thank :)

**Comment by vitchyr** [comment]
Closed with: https://github.com/vitchyr/viskit/commit/88b7cd7d94fa97ab31bb0681f51ecd160effaa93
