### ISSUE TITLE
Select best paths 

### ISSUE THREAD

**Issue by richardrl** [vitchyr/viskit#3]
Is there any fast way to find the folder names of the best experiments? Th filtering options, select best options, didn't do anything for me 

Or, if there's a way to expand the name shown on hover, that could work as well.
 
![image](https://user-images.githubusercontent.com/5181990/54737488-781a0380-4b6d-11e9-9132-8da47e687857.png)

**Comment by vitchyr** [comment]
What are you filtering by? If you do exp_name, that should do it. Another
option (which is what I do) is to filter by unique_id and then use grep in
a terminal to find which folder it belongs to. Note that while you can't
copy/paste from the website (let met know if yu figure out how to), the
best key gets printed in the terminal window running viskit.

**Comment by richardrl** [comment]
I see, so if you filter by best and watch the terminal screen, you can get the top exp_name that is argmaxed over value at the final epoch.

I would like to select the experiments that converge first and also select more than 1 (top k) expnames. Is that not possible at the moment?

**Comment by vitchyr** [comment]
No, you'd have to implement it yourself. I'll close this issue, but from free to make sure new one for that feature request or to make a PR for it.
