### ISSUE TITLE
Hover label with long name is truncated

### ISSUE THREAD

**Issue by jendelel** [vitchyr/viskit#9]
Hi Vitchyr, 

I love viskit. Do you think it would be possible to show the whole legend name when hovering over the data? Right now, it truncates shows only the beginning as shown below.

I found this [issue](https://github.com/plotly/plotly.js/issues/460) on plotly, but adding 

```
hoverlabel=dict(namelength=-1)
```
to `go.Scatter` function for values ([link](https://github.com/vitchyr/viskit/blob/master/viskit/frontend.py#L237) in `make_plot` function did not fix it for me .

Since viskit is relatively complex I thought I might be missing something that you could help me to spot.

Thanks a lot, 
Lukas

**Comment by jendelel** [comment]
Here is a screenshot of what I have in mind.
![viskit_labels_truncated](https://user-images.githubusercontent.com/16251857/63159696-67869000-c01c-11e9-8fcf-8e412866bc31.png)

**Comment by vitchyr** [comment]
This seems like a plotly-specific issue, and I don't have an specific ideas
for how to address it. If you figure out how to do this, please make a PR
and I'll be happy to accept it!

**Comment by jendelel** [comment]
Hi Vitchyr, 

upgrading both Python and embedded JS version of Plotly fixed it for me. I'd be happy to send you a PR if you want (it's 3 lines change). 

I noticed that the plots look different and hovering shows only one trace instead of all of them. There are probably more things that changed between the versions. I will stick to the new one as I like the full labels.

Let me know if you want me to send you the PR.

Lukas

**Comment by vitchyr** [comment]
Would you mind sharing a screenshot of what it looks like?

**Comment by jendelel** [comment]
![viskit_new_plotly](https://user-images.githubusercontent.com/16251857/63362257-d6901b80-c371-11e9-9ec1-126a66a01185.png)

**Comment by vitchyr** [comment]
Could you submit a PR? I'll look over it and then decide.
